import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',args:['--no-sandbox']});
const page=await browser.newPage({viewport:{width:1440,height:1100}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto(process.env.GAME_URL||'http://127.0.0.1:5173');await page.getByRole('button',{name:'TAKE YOUR STAND'}).click();
await page.waitForTimeout(200);
await page.keyboard.down('D');await page.waitForTimeout(250);await page.keyboard.up('D');
assert(await page.evaluate(()=>window.elowen.x>520),'movement');
await page.keyboard.down('Space');await page.waitForTimeout(100);assert(await page.evaluate(()=>window.elowen.y<400),'jump');await page.keyboard.up('Space');await page.waitForTimeout(900);
await page.keyboard.down('S');await page.waitForTimeout(80);assert(await page.evaluate(()=>window.elowen.crouching),'crouch');await page.keyboard.up('S');
await page.evaluate(()=>{const s=window.elowen;s.enemies=[{x:s.x+65,hp:76,max:76,next:10,speed:0,kind:0}];s.timer=999;});
await page.keyboard.down('J');await page.waitForTimeout(80);await page.keyboard.up('J');assert(await page.evaluate(()=>window.elowen.enemies[0].hp<76),'sword damage');
await page.evaluate(()=>{const s=window.elowen;s.enemies=[{x:s.x+35,hp:76,max:76,next:.1,speed:0,kind:0}];s.hp=100;s.stamina=100;});
await page.keyboard.down('K');await page.waitForTimeout(250);await page.keyboard.up('K');assert(await page.evaluate(()=>window.elowen.hp===100&&window.elowen.stamina<100),'shield blocks damage');
await page.evaluate(()=>{const s=window.elowen;s.enemies=[{x:s.x+140,hp:76,max:76,next:10,speed:0,kind:0}];});await page.keyboard.down('L');await page.waitForTimeout(400);await page.keyboard.up('L');assert(await page.evaluate(()=>window.elowen.enemies[0].hp<76&&window.elowen.energy<100),'spell hits and costs energy');
await page.evaluate(()=>{const s=window.elowen;s.survivors=[{x:76,t:0}];});await page.waitForTimeout(100);assert(await page.evaluate(()=>window.elowen.rescued>0),'survivor escape');
await page.keyboard.press('Escape');assert(await page.getByText('Paused',{exact:true}).isVisible());await page.getByRole('button',{name:'RESUME'}).click();
await page.evaluate(()=>{const s=window.elowen;s.enemies=[];s.survivors=[];s.spawned=s.total;});await page.getByRole('button',{name:'Crescent cut'}).click();assert(await page.evaluate(()=>window.elowen.wave===2&&window.elowen.damage>27),'wave upgrade');
await page.evaluate(()=>{const s=window.elowen;s.enemies=[];s.survivors=[];s.spawned=s.total;});await page.getByRole('button',{name:'Ember mastery'}).click();assert(await page.evaluate(()=>window.elowen.wave===3),'third wave');
await page.screenshot({path:'/tmp/elowen-game.png'});
await page.evaluate(()=>{const s=window.elowen;s.enemies=[];s.survivors=[];s.spawned=s.total;});await page.getByRole('button',{name:'STAND AGAIN'}).click();assert(await page.evaluate(()=>window.elowen.wave===1),'victory restart');
await page.evaluate(()=>window.elowen.hp=0);await page.getByRole('button',{name:'TRY AGAIN'}).click();assert(await page.evaluate(()=>window.elowen.hp===100),'defeat restart');
assert.deepEqual(errors,[]);console.log('PASS: movement, jump, sword, shield, Ember Strike, survivor escape, pause, both upgrades, victory, defeat, restart; no browser errors.');await browser.close();
