import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',args:['--no-sandbox']});
const page=await browser.newPage({viewport:{width:1440,height:1100}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto(process.env.GAME_URL||'http://127.0.0.1:5173');await page.getByRole('button',{name:'TAKE YOUR STAND'}).click();
await page.waitForTimeout(200);
await page.keyboard.down('D');await page.waitForTimeout(250);await page.keyboard.up('D');
assert(await page.evaluate(()=>window.elowen.x>520),'movement');
await page.keyboard.down('Space');await page.waitForTimeout(100);assert(await page.evaluate(()=>window.elowen.y<400),'jump');await page.keyboard.up('Space');await page.waitForFunction(()=>window.elowen.y>=422);
await page.keyboard.down('S');await page.waitForTimeout(80);assert(await page.evaluate(()=>window.elowen.crouching),'crouch');await page.keyboard.up('S');
await page.evaluate(()=>{const s=window.elowen;s.enemies=[{x:s.x+65,hp:76,max:76,next:10,speed:0,kind:0}];s.timer=999;});
await page.keyboard.down('J');await page.waitForTimeout(80);await page.keyboard.up('J');assert(await page.evaluate(()=>window.elowen.enemies[0].hp<76),'sword damage');
await page.evaluate(()=>{const s=window.elowen;s.enemies=[{x:s.x+35,hp:76,max:76,next:.1,speed:0,kind:0}];s.hp=100;s.stamina=100;});
await page.keyboard.down('L');await page.waitForTimeout(250);await page.keyboard.up('L');assert(await page.evaluate(()=>window.elowen.hp===100&&window.elowen.stamina<100),'shield blocks damage');
await page.evaluate(()=>{const s=window.elowen;s.enemies=[{x:s.x+140,hp:76,max:76,next:10,speed:0,kind:0}];});await page.keyboard.down('E');await page.waitForTimeout(400);await page.keyboard.up('E');assert(await page.evaluate(()=>window.elowen.enemies[0].hp<76&&window.elowen.energy<100),'spell hits and costs energy');
// Locked spells and reserved bash must not spend resources.
await page.evaluate(()=>{const s=window.elowen;s.energy=100;s.stamina=100;s.enemies=[];});
await page.keyboard.press('1');await page.keyboard.press('K');
assert(await page.evaluate(()=>window.elowen.energy===100&&window.elowen.stamina===100),'locked actions');
await page.evaluate(()=>{const s=window.elowen;s.survivors=[{x:76,t:0}];});await page.waitForTimeout(100);assert(await page.evaluate(()=>window.elowen.rescued>0),'survivor escape');
await page.keyboard.press('Escape');assert(await page.getByText('Paused',{exact:true}).isVisible());await page.getByRole('button',{name:'RESUME'}).click();
await page.evaluate(()=>{const s=window.elowen;s.enemies=[];s.survivors=[];s.spawned=s.total;});await page.locator('[data-up="bash"]').click();await page.locator('#next-wave').click();assert(await page.evaluate(()=>window.elowen.wave===2&&window.elowen.upgrades.includes('bash')),'wave upgrade');
await page.evaluate(()=>{const s=window.elowen;s.enemies=[];s.survivors=[];s.spawned=s.total;});await page.locator('[data-up="volley"]').click();await page.locator('#next-wave').click();assert(await page.evaluate(()=>window.elowen.wave===3),'third wave');
// Actual upgrade unlocks the reserved K ability.
await page.evaluate(()=>{const s=window.elowen;s.enemies=[{x:s.x+65,hp:100,max:100,next:10,speed:0,kind:0}];s.timer=999;s.stamina=100;});
await page.keyboard.press('K');await page.waitForTimeout(80);
assert(await page.evaluate(()=>window.elowen.enemies[0].x>window.elowen.x+100&&window.elowen.enemies[0].stunned>0&&window.elowen.stamina<100),'Shield Bash pushes, staggers and costs stamina');
// Set up remaining unlocks to exercise every binding in isolation.
await page.evaluate(()=>window.elowen.upgrades.push('ice','ward','stone','vines'));
async function fixture(enemies){await page.evaluate(es=>{const s=window.elowen;s.enemies=es.map(dx=>({x:s.x+dx,hp:160,max:160,next:10,speed:0,kind:0}));s.energy=100;s.spellCooldowns={};s.shots=[];s.wall=null;},enemies)}
await fixture([160,200]);await page.keyboard.press('1');await page.waitForTimeout(320);
assert(await page.evaluate(()=>window.elowen.enemies.every(e=>e.hp<160)&&window.elowen.energy<100),'Ice Lance impact and splash');
await fixture([560]);await page.keyboard.press('1');await page.waitForTimeout(900);
assert(await page.evaluate(()=>window.elowen.enemies[0].hp<160),'Ice Lance explodes on a miss at range');
await fixture([35]);await page.evaluate(()=>{window.elowen.hp=100;window.elowen.inv=0;window.elowen.enemies[0].next=.1;});await page.keyboard.press('2');await page.waitForTimeout(250);
assert(await page.evaluate(()=>window.elowen.wardTime>0&&window.elowen.hp===94.5),'Warrior’s Shield halves attack damage');
await fixture([140,200,260,320]);await page.keyboard.press('3');await page.waitForTimeout(80);
assert(await page.evaluate(()=>window.elowen.enemies.every(e=>e.hp===141)),'Hunter’s Volley strikes four targets');
await fixture([70,140,-70,300]);await page.keyboard.press('4');await page.waitForTimeout(80);
assert(await page.evaluate(()=>window.elowen.enemies[0].hp<160&&window.elowen.enemies[1].hp<160&&window.elowen.enemies[2].hp===160&&window.elowen.enemies[3].hp===160),'Stoneshard Barrage hits only its forward cone');
await fixture([140]);await page.evaluate(()=>window.elowen.enemies[0].next=.1);await page.keyboard.press('5');await page.waitForTimeout(250);
assert(await page.evaluate(()=>window.elowen.wall&&window.elowen.wall.hp<110&&window.elowen.enemies[0].x===window.elowen.x+140),'Vine wall intercepts and takes attacks');
await page.evaluate(()=>{const s=window.elowen;s.wall.hp=1;s.enemies[0].next=0;});await page.waitForTimeout(100);assert(await page.evaluate(()=>window.elowen.wall===null),'Vine wall can be destroyed');
await fixture([]);await page.keyboard.press('E');const after=await page.evaluate(()=>window.elowen.energy);await page.keyboard.press('E');assert(await page.evaluate(()=>window.elowen.energy>=0)&&await page.evaluate(()=>window.elowen.energy)>after-1,'cooldown prevents duplicate cast');
await page.evaluate(()=>{window.elowen.energy=0;window.elowen.spellCooldowns={};});await page.keyboard.press('4');assert(await page.evaluate(()=>window.elowen.energy<2),'insufficient Chaos blocks cast');
await fixture([]);await page.getByRole('button',{name:/Wall of Vines, key 5/}).click();assert(await page.evaluate(()=>!!window.elowen.wall),'clickable spell controls');
await page.screenshot({path:'/tmp/elowen-game.png'});
await page.evaluate(()=>{const s=window.elowen;s.wave=8;s.enemies=[];s.survivors=[];s.spawned=s.total;});await page.getByRole('button',{name:'STAND AGAIN'}).click();assert(await page.evaluate(()=>window.elowen.wave===1),'victory restart');
await page.evaluate(()=>window.elowen.hp=0);await page.getByRole('button',{name:'TRY AGAIN'}).click();assert(await page.evaluate(()=>window.elowen.hp===100),'defeat restart');assert(await page.evaluate(()=>!window.elowen.wall&&window.elowen.wardTime===0&&!window.elowen.upgrades.length),'restart clears spell state');
assert.deepEqual(errors,[]);console.log('PASS: movement, jump, sword, shield, Ember Strike, survivor escape, pause, upgrades, all six spell bindings and effects, unlock gates, cooldowns, Shield Bash, victory, defeat, restart; no browser errors.');await browser.close();
