import Phaser from 'phaser';
import './style.css';
const W=1280,H=720,G=422;
type Enemy={x:number,hp:number,max:number,next:number,speed:number,kind:number};
type Survivor={x:number,t:number};
type Shot={x:number,y:number,dir:number,life:number};
type Particle={x:number,y:number,vx:number,vy:number,life:number,color:number};
const overlay=document.querySelector<HTMLDivElement>('#overlay')!;
let muted=true;
let audio:AudioContext|undefined;
function tone(freq:number,duration=.08){if(muted)return;audio??=new AudioContext();void audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type='triangle';o.frequency.value=freq;o.connect(g);g.connect(audio.destination);g.gain.setValueAtTime(.04,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.start();o.stop(audio.currentTime+duration);}
document.querySelector('#sound')!.addEventListener('click',()=>{muted=!muted;document.querySelector('#sound')!.textContent=muted?'SOUND OFF':'SOUND ON';tone(440)});
class Stand extends Phaser.Scene{
 spritePool:Phaser.GameObjects.Image[]=[];spriteIndex=0;art!:Phaser.GameObjects.Graphics;hud!:Phaser.GameObjects.Graphics;labels!:Phaser.GameObjects.Text;keys!:Record<string,Phaser.Input.Keyboard.Key>;
 phase='title';wave=1;x=500;y=G;vy=0;face=1;hp=100;stamina=100;energy=100;damage=27;spellDamage=43;shieldCost=14;rescued=0;lost=0;kills=0;spawned=0;total=0;timer=0;clock=0;swing=0;attackCd=0;spellCd=0;inv=0;blocking=false;crouching=false;enemies:Enemy[]=[];survivors:Survivor[]=[];shots:Shot[]=[];particles:Particle[]=[];paused=false;touch=new Set<string>();upgrades:string[]=[];castCount=0;waveKills=0;
 preload(){this.load.image('forest',new URL('forest.png',document.baseURI).href);this.load.image('characters',new URL('characters.png',document.baseURI).href)}
 create(){this.background();if(this.textures.exists('characters')){const tex=this.textures.get('characters');const src=tex.getSourceImage() as HTMLImageElement;const canvas=document.createElement('canvas');canvas.width=src.width;canvas.height=src.height;const ctx=canvas.getContext('2d')!;ctx.drawImage(src,0,0);const pixels=ctx.getImageData(0,0,src.width,src.height).data;for(let f=0;f<4;f++){let minX=src.width,minY=src.height,maxX=0,maxY=0;for(let y=0;y<src.height;y++)for(let x=Math.floor(f*src.width/4);x<Math.floor((f+1)*src.width/4);x++){if(pixels[(y*src.width+x)*4+3]>90){minX=Math.min(minX,x);minY=Math.min(minY,y);maxX=Math.max(maxX,x);maxY=Math.max(maxY,y)}}tex.add('figure'+f,0,minX,minY,maxX-minX+1,maxY-minY+1)}}this.art=this.add.graphics().setDepth(2);this.hud=this.add.graphics().setDepth(3);this.labels=this.add.text(35,26,'',{fontFamily:'Arial',fontSize:'12px',color:'#dedaca',lineSpacing:8}).setDepth(10);this.keys=this.input.keyboard!.addKeys('A,D,S,SPACE,J,K,L,ESC') as Record<string,Phaser.Input.Keyboard.Key>;this.input.keyboard!.addCapture(['SPACE','A','D','S','J','K','L']);this.title();(window as unknown as {elowen:Stand}).elowen=this;}
 background(){if(this.textures.exists('forest'))this.add.image(W/2,H/2,'forest').setDisplaySize(W,H);else{const g=this.add.graphics();g.fillGradientStyle(0x102b32,0x253d37,0x172729,0x17302c,1);g.fillRect(0,0,W,H);let seed=7;const rand=()=>{seed=(seed*16807)%2147483647;return seed/2147483647};for(let layer=0;layer<3;layer++){for(let i=0;i<22;i++){const x=rand()*W;g.fillStyle([0x34524e,0x233e3b,0x152e2c][layer]);g.fillRect(x,60+rand()*160,20+layer*18,550);g.fillTriangle(x-120,140,x+110,150,x,20)}}g.fillStyle(0x3a4b3d);g.fillRect(0,G,W,34);g.fillStyle(0x182827);g.fillRect(0,G+34,W,H-G);for(let i=0;i<60;i++){g.fillStyle(i%2?0x65705a:0x4f5d4c);g.fillRect(i*24,G,22,8)}for(let i=0;i<3;i++){g.fillStyle(0x0d2024);g.fillEllipse(90+i*165,G+115,120,155)}}const g=this.add.graphics();g.fillStyle(0x061619,.25);g.fillRect(0,0,W,100);g.fillGradientStyle(0x081519,0x081519,0x081519,0x081519,0,0,.8,.8);g.fillRect(0,630,W,90);g.fillStyle(0x817d58);g.fillRect(351,G-100,8,100);g.fillStyle(0xae5942);g.fillTriangle(359,G-98,401,G-87,359,G-64);g.fillStyle(0x334641);g.fillRect(310,G-10,76,10);this.add.text(300,G+25,'← THE CROSSING',{fontFamily:'Arial',fontSize:'10px',color:'#a8ae8a',letterSpacing:2});}
 title(){overlay.innerHTML=`<div class="panel"><div class="gold">THE LAST LIGHT AT GREYFALL</div><h2>They’re counting on you.</h2><p>The dead are coming. Hold the bridge while the survivors flee.<br>Your sword is their last defence. Your Chaos is their last hope.</p><button class="primary" id="begin">TAKE YOUR STAND →</button><p>Three waves · Sword & shield · Chaosbound magic</p></div>`;document.querySelector('#begin')!.addEventListener('click',()=>this.begin());}
 controls(){const bar=document.createElement('div');bar.className='touch';bar.innerHTML='<div><button data-key="A">◀</button><button data-key="D">▶</button><button data-key="SPACE">↑</button><button data-key="S">↓</button></div><div><button data-key="J">⚔</button><button data-key="K">▣</button><button data-key="L">✦</button></div>';document.querySelector('.game-shell')!.append(bar);bar.querySelectorAll<HTMLButtonElement>('button').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);this.touch.add(b.dataset.key!)};b.onpointerup=b.onpointercancel=()=>this.touch.delete(b.dataset.key!)});}
 begin(){this.hp=this.stamina=this.energy=100;this.x=500;this.y=G;this.vy=0;this.wave=1;this.rescued=this.lost=this.kills=0;this.damage=27;this.spellDamage=43;this.shieldCost=14;this.upgrades=[];this.shots=[];this.particles=[];this.attackCd=this.spellCd=this.inv=this.swing=0;this.paused=false;this.castCount=0;if(!document.querySelector('.touch'))this.controls();this.startWave();}
 startWave(){overlay.innerHTML='';this.phase='play';this.enemies=[];this.survivors=Array.from({length:5},(_,i)=>({x:680+i*48,t:i*.4}));this.spawned=0;this.waveKills=0;this.total=5+this.wave*3;this.timer=1.4;this.clock=0;this.energy=100;this.stamina=100;this.hp=Math.min(100,this.hp+22);}
 down(k:string){return this.keys[k].isDown||this.touch.has(k)}
 burst(x:number,y:number,color:number,n=12){for(let i=0;i<n;i++)this.particles.push({x,y,vx:Phaser.Math.Between(-140,140),vy:Phaser.Math.Between(-180,40),life:Phaser.Math.FloatBetween(.2,.65),color})}
 hurt(e:Enemy,d:number){e.hp-=d;this.burst(e.x,G-40,0xb8c78b,8);e.x+=this.face*15;if(e.hp<=0){this.kills++;this.waveKills++;this.burst(e.x,G-30,0xc69d57,16);tone(100)}}
 upgrade(){this.phase='upgrade';const options=this.wave===1?[['Crescent cut','A wider sword sweep. +40% sword damage.','sword'],['Warrior’s Shield','Chaosbound protection. Blocking costs 40% less stamina.','shield'],['Ice Lance','Ember Strike becomes an explosive ice lance every third cast.','ice']]:[['Hunter’s Volley','Every cast adds radiant bolts that seek nearby enemies.','volley'],['Second wind','Restore health fully. Regenerate health during the final wave.','heal'],['Ember mastery','+50% spell damage. Reduce Chaos cost to 16.','ember']];overlay.innerHTML=`<div class="panel"><div class="gold">WAVE ${this.wave} COMPLETE · ${this.rescued} SURVIVORS SAFE</div><h2>Strength for the next stand.</h2><p>Choose an ability or a Chaosbound spell.</p><div class="choices">${options.map(o=>`<button class="choice" data-up="${o[2]}"><b>${o[0]}</b><span>${o[1]}</span></button>`).join('')}</div></div>`;overlay.querySelectorAll<HTMLButtonElement>('[data-up]').forEach(b=>b.onclick=()=>{const u=b.dataset.up!;this.upgrades.push(u);if(u==='sword')this.damage*=1.4;if(u==='shield')this.shieldCost*=.6;if(u==='heal')this.hp=100;if(u==='ember')this.spellDamage*=1.5;this.wave++;this.startWave()})}
 end(win:boolean){this.phase=win?'win':'dead';overlay.innerHTML=`<div class="panel"><div class="gold">${win?'THE CROSSING IS SAFE':'GREYFALL REMEMBERS'}</div><h2>${win?'You held the line.':'The last light fades.'}</h2><p>${this.rescued} survivors escaped · ${this.kills} undead defeated${this.lost?` · ${this.lost} survivors lost`:''}<br>${win?'For one more night, there is hope.':'Rise again. They still need you.'}</p><button class="primary" id="retry">${win?'STAND AGAIN':'TRY AGAIN'} →</button></div>`;document.querySelector('#retry')!.addEventListener('click',()=>this.begin())}
 update(_time:number,delta:number){const dt=Math.min(delta/1000,.04);if(Phaser.Input.Keyboard.JustDown(this.keys.ESC)&&this.phase==='play'){this.paused=!this.paused;overlay.innerHTML=this.paused?'<div class="panel"><div class="gold">A MOMENT OF STILLNESS</div><h2>Paused</h2><p>Press Escape to return to the crossing.</p><button class="primary" id="resume">RESUME</button></div>':'';document.querySelector('#resume')?.addEventListener('click',()=>{this.paused=false;overlay.innerHTML=''})}if(this.phase==='play'&&!this.paused)this.tick(dt);this.draw();}
 tick(dt:number){this.clock+=dt;this.timer-=dt;this.attackCd-=dt;this.spellCd-=dt;this.inv-=dt;this.swing=Math.max(0,this.swing-dt);this.blocking=this.down('K')&&this.stamina>5;this.crouching=this.down('S')&&this.y>=G;const move=(this.down('D')?1:0)-(this.down('A')?1:0);if(move){this.face=move;this.x=Phaser.Math.Clamp(this.x+move*dt*(this.blocking||this.crouching?90:215),355,1000)}if(this.down('SPACE')&&this.y>=G&&!this.crouching){this.vy=-450;this.y-=1;tone(260)}this.vy+=1100*dt;this.y+=this.vy*dt;if(this.y>=G){this.y=G;this.vy=0}this.stamina=Math.min(100,this.stamina+dt*(this.blocking?4:24));this.energy=Math.min(100,this.energy+dt*7);if(this.upgrades.includes('heal'))this.hp=Math.min(100,this.hp+dt*1.5);
 if(this.down('J')&&this.attackCd<=0&&!this.blocking){this.attackCd=.42;this.swing=.22;tone(180);this.enemies.forEach(e=>{if((e.x-this.x)*this.face>-20&&(e.x-this.x)*this.face<115&&Math.abs(this.y-G)<100)this.hurt(e,this.damage)})}
 const cost=this.upgrades.includes('ember')?16:24;if(this.down('L')&&this.spellCd<=0&&this.energy>=cost&&!this.blocking){this.energy-=cost;this.spellCd=.75;this.castCount++;this.shots.push({x:this.x+this.face*30,y:this.y-48,dir:this.face,life:2});this.burst(this.x+this.face*30,this.y-48,0xfba15b);tone(520,.15)}
 if(this.timer<=0&&this.spawned<this.total){const kind=this.wave===3&&this.spawned%4===0?2:this.wave>1&&this.spawned%3===0?1:0;const max=kind===2?145:kind===1?60:76;this.enemies.push({x:1260,hp:max,max,next:0,speed:kind===1?88:kind===2?32:45+this.wave*5,kind});this.spawned++;this.timer=Math.max(.8,2.2-this.wave*.25)}
 for(const s of this.survivors){s.t+=dt;s.x-=dt*75;if(s.x<75){this.rescued++;s.x=-1000}if(this.enemies.some(e=>Math.abs(e.x-s.x)<25)){this.lost++;this.burst(s.x,G-40,0xe49276);s.x=-1000}}this.survivors=this.survivors.filter(s=>s.x>-500);
 for(const e of this.enemies){e.next-=dt;const near=Math.abs(e.x-this.x)<48&&Math.abs(this.y-G)<72;if(!near)e.x-=e.speed*dt;if(near&&e.next<=0){e.next=1.05;if(this.blocking&&(e.x-this.x)*this.face>=-8&&this.stamina>=this.shieldCost){this.stamina-=this.shieldCost;e.x+=this.face*28;this.burst(this.x+this.face*25,this.y-40,0xe9d794);tone(360)}else if(this.inv<=0){this.hp-=e.kind===2?20:11;this.inv=.55;this.burst(this.x,this.y-40,0xd85d4d);tone(85,.14)}}if(e.x<300){this.hp-=20;e.hp=0;this.burst(e.x,G-40,0xd85d4d)}}
 for(const s of this.shots){s.x+=s.dir*510*dt;s.life-=dt;this.particles.push({x:s.x,y:s.y,vx:-s.dir*30,vy:-15,life:.2,color:0xf3a25d});const e=this.enemies.find(e=>e.hp>0&&Math.abs(e.x-s.x)<25&&Math.abs(G-44-s.y)<56);if(e){this.hurt(e,this.spellDamage);s.life=0;if(this.upgrades.includes('ice')&&this.castCount%3===0){this.burst(e.x,G-45,0x8cd7e5,30);this.enemies.filter(t=>t!==e&&Math.abs(t.x-e.x)<100).forEach(t=>this.hurt(t,this.spellDamage*.7))}if(this.upgrades.includes('volley'))this.enemies.filter(t=>t!==e&&Math.abs(t.x-e.x)<230).slice(0,3).forEach(t=>{this.hurt(t,22);this.burst(t.x,G-45,0xf6e4b0)})}}
 this.shots=this.shots.filter(s=>s.life>0);this.enemies=this.enemies.filter(e=>e.hp>0);for(const p of this.particles){p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=220*dt}this.particles=this.particles.filter(p=>p.life>0);if(this.hp<=0)this.end(false);else if(this.spawned>=this.total&&!this.enemies.length&&!this.survivors.length){if(this.wave===3)this.end(true);else this.upgrade()}}
 sprite(x:number,y:number,zombie=false,kind=0,t=0,face=1,crouch=false,survivor=false){const g=this.art;if(!survivor&&this.textures.exists('characters')){let im=this.spritePool[this.spriteIndex++];if(!im){im=this.add.image(0,0,'characters').setDepth(1);this.spritePool.push(im)}const frame='figure'+(zombie?kind+1:0);im.setTexture('characters',frame).setOrigin(.5,1).setPosition(x,y).setFlipX(face<0).setVisible(true);const h=(kind===2?124:104)*(crouch?.65:1);const ratio=im.frame.width/im.frame.height;im.setDisplaySize(h*ratio,h);im.setAngle(Math.sin(t*10)*(zombie?2:1));g.fillStyle(0x061516,.35);g.fillEllipse(x,y+2,54,10);return}const scale=kind===2?1.35:1;const unit=2.6*scale;const top=y-(crouch?49:78)*scale;const rect=(a:number,b:number,w:number,h:number,c:number)=>{g.fillStyle(c);g.fillRect(Math.round(x+a*unit*face-(face<0?w*unit:0)),Math.round(top+b*unit*(crouch?.63:1)),w*unit,h*unit*(crouch?.63:1))};g.fillStyle(0x061516,.35);g.fillEllipse(x,y+2,52*scale,10);const skin=zombie?0x829978:0xd6ac83;const dark=zombie?0x38473d:0x253445;const cloth=survivor?0x9b8566:zombie?kind===1?0x716451:0x59625a:0x4b7777;const stride=Math.sin(t*10)*2;rect(-5,22,4,7,dark);rect(2,22,4,7,dark);rect(-6+stride,28,6,2,0x342e2a);rect(2-stride,28,6,2,0x342e2a);if(!zombie&&!survivor){rect(-8,10,6,15,0x913f3b);rect(-9,16,3,10,0x6d3033)}rect(-5,10,11,12,cloth);rect(-4,12,9,2,0x82908b);rect(-5,20,11,2,0x9b8458);rect(-3,8,6,3,skin);rect(-4,2,9,7,skin);rect(-5,1,10,3,zombie?0x3d4437:0x57402f);rect(-5,3,3,9,zombie?0x48543f:0x6b4932);rect(2,5,2,1,zombie?0xe4c477:0x142b2d);rect(5,6,1,2,skin);rect(-8,11,3,9,cloth);rect(-8,19,3,3,skin);rect(6,11,3,zombie?5:8,cloth);rect(7,zombie?15:18,zombie?7:3,3,skin);if(zombie){rect(-1,14,3,4,0x424838);rect(3,19,2,3,0x8c5c4e)}else if(!survivor){rect(7,20,2,7,0x9b8553);rect(5,20,6,1,0xd8bd79);rect(8,10,2,10,0xd0dbcf);rect(8,9,1,1,0xf9f1c8);rect(-12,14,6,10,0xb49a64);rect(-11,15,4,8,0x4c6360);rect(-9,16,1,6,0xc2b37d)}}
 draw(){this.spriteIndex=0;this.spritePool.forEach(im=>im.setVisible(false));const g=this.art;g.clear();for(let i=0;i<20;i++){const x=(i*79+Math.sin(Date.now()/2500+i)*20)%W;g.fillStyle(0xc6b878,.35);g.fillRect(x,180+(i*37)%290,2,2)}for(const s of this.survivors)this.sprite(s.x,G,false,0,s.t,-1,false,true);for(const e of this.enemies){this.sprite(e.x,G,true,e.kind,this.clock,-1);g.fillStyle(0x15211e);g.fillRect(e.x-21,G-(e.kind===2?115:88),42,3);g.fillStyle(0x9c7754);g.fillRect(e.x-21,G-(e.kind===2?115:88),42*e.hp/e.max,3)}if(this.inv<=0||Math.floor(this.inv*20)%2===0)this.sprite(this.x,this.y,false,0,this.phase==='play'&&(this.down('A')||this.down('D'))?this.clock:0,this.face,this.crouching);if(this.blocking){g.lineStyle(3,0xf0ce83,.7);g.beginPath();g.arc(this.x+this.face*16,this.y-39,31,this.face>0?-1.2:1.9,this.face>0?1.2:4.4);g.strokePath()}if(this.swing>0){g.lineStyle(7,0xe6ddbd,this.swing/.22);g.beginPath();g.arc(this.x,this.y-43,85,this.face>0?-1:2.1,this.face>0?1:4.2);g.strokePath();g.lineStyle(2,0xffffff,.7);g.beginPath();g.arc(this.x,this.y-43,92,this.face>0?-.8:2.3,this.face>0?.8:4);g.strokePath()}for(const s of this.shots){g.fillStyle(0xe56c35,.2);g.fillCircle(s.x,s.y,20);g.fillStyle(0xf89d43);g.fillRect(s.x-10,s.y-7,18,14);g.fillStyle(0xffecc0);g.fillRect(s.x-3,s.y-4,8,8)}for(const p of this.particles){g.fillStyle(p.color,Math.min(1,p.life*3));g.fillRect(p.x,p.y,3,3)}const h=this.hud;h.clear();h.fillStyle(0x0c1e22,.88);h.fillRoundedRect(20,18,350,89,4);const bar=(y:number,v:number,c:number)=>{h.fillStyle(0x30433f);h.fillRect(125,y,210,5);h.fillStyle(c);h.fillRect(125,y,210*Math.max(0,v)/100,5)};bar(37,this.hp,0xb76051);bar(59,this.stamina,0xb8a26c);bar(81,this.energy,0x649caa);this.labels.setText(`HEALTH\nSTAMINA\nCHAOS ENERGY`);h.fillStyle(0x0c1e22,.85);h.fillRoundedRect(940,18,320,89,4);const status=this.phase==='title'?'THE BRIDGE AT GREYFALL':`WAVE ${this.wave} / 3   ·   ${this.phase==='play'?'HOLD THE LINE':this.phase==='win'?'CROSSING SECURED':'THE CROSSING'}`;if(!this.data.get('statusText')){this.data.set('statusText',this.add.text(962,31,'',{fontFamily:'Arial',fontSize:'12px',color:'#dbc99d',lineSpacing:15}).setDepth(10));this.data.set('bottomText',this.add.text(W/2,676,'',{fontFamily:'Arial',fontSize:'12px',color:'#cdc8ac'}).setOrigin(.5).setDepth(10))}(this.data.get('statusText') as Phaser.GameObjects.Text).setText(`${status}\n${this.rescued} SAFE   ·   ${this.kills} UNDEAD DEFEATED`);(this.data.get('bottomText') as Phaser.GameObjects.Text).setText(this.phase==='play'?this.clock<5?'SURVIVORS ARE CROSSING. KEEP THE DEAD FROM THE BRIDGE.':`${this.total-this.waveKills} ENEMIES THIS WAVE  ·  EMBER STRIKE ${this.spellCd>0?'RECHARGING':'READY'}`:'SWORD & SHIELD  /  EMBER STRIKE');}
}
new Phaser.Game({type:Phaser.AUTO,parent:'game',width:W,height:H,backgroundColor:'#162e2f',pixelArt:true,roundPixels:true,scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH},scene:Stand,audio:{noAudio:true}});
